# Generated by Django 5.2.8 on 2026-02-18 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0206_pricelistitem_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pricelistitem",
            new_name="product_pri_price_l_2a35bf_idx",
            old_name="product_pri_price_l_is_valid_idx",
        ),
    ]
