# Generated by Django 5.2.8 on 2026-02-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("invoice", "0012_invoice_purchase_order_invoice_type_and_more"),
        ("shipping", "0037_merge_20250630_1332"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrived_at", models.DateTimeField(null=True)),
                ("departed_at", models.DateTimeField(null=True)),
                ("carrier", models.CharField(null=True)),
                ("tracking_number", models.CharField(null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="inbound_shipments",
                        to="account.address",
                    ),
                ),
                (
                    "shipping_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="invoice.invoice",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="outbound_shipments",
                        to="account.address",
                    ),
                ),
            ],
        ),
    ]
