# Generated by Django 5.2.8 on 2026-02-06 10:13

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0038_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_cost_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0.0"),
                max_digits=20,
                null=True,
            ),
        ),
    ]
