# Generated by Django 5.2.8 on 2026-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0039_add_shipment_cost_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="inco_term",
            field=models.CharField(
                choices=[
                    ("EXW", "Ex Works"),
                    ("FCA", "Free Carrier"),
                    ("CPT", "Carriage Paid To"),
                    ("CIP", "Carriage and Insurance Paid To"),
                    ("DAP", "Delivered At Place"),
                    ("DPU", "Delivered at Place Unloaded"),
                    ("DDP", "Delivered Duty Paid"),
                    ("FAS", "Free Alongside Ship"),
                    ("FOB", "Free On Board"),
                    ("CFR", "Cost and Freight"),
                    ("CIF", "Cost Insurance and Freight"),
                ],
                default="DDP",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
