# Generated by Django 5.2.8 on 2026-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0042_add_shipment_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="tracking_number",
            new_name="tracking_url",
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_url",
            field=models.CharField(
                blank=True,
                help_text="Tracking URL or number. Can be used to fetch shipment status from carrier APIs.",
                null=True,
            ),
        ),
    ]
