# Generated by Django 5.2.8 on 2026-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0043_rename_tracking_number_to_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="type",
            field=models.CharField(
                choices=[
                    ("price", "Price based shipping"),
                    ("weight", "Weight based shipping"),
                    ("manual", "Manual shipping"),
                ],
                max_length=30,
            ),
        ),
    ]
