# Generated by Django 5.2.8 on 2026-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0043_sitesettings_use_legacy_update_webhook_emission"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="invoice_product_code_attribute",
            field=models.CharField(
                blank=True,
                default="product-code",
                help_text="Product attribute slug to use as product code in invoice webhooks. Examples: 'product-code', 'supplier-code', 'vendor-code'",
                max_length=255,
            ),
        ),
    ]
