# Generated by Django 5.2.8 on 2026-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0035_alter_warehouse_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="is_owned",
            field=models.BooleanField(default=False),
        ),
    ]
