# Generated by Django 5.2.8 on 2026-02-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("warehouse", "0036_warehouse_is_owned"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="purchase_order_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="allocations",
                to="inventory.purchaseorderitem",
            ),
        ),
        migrations.CreateModel(
            name="AllocationSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_sources",
                        to="warehouse.allocation",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_sources",
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("allocation", "purchase_order_item")},
            },
        ),
    ]
