# Generated by Django 5.2.8 on 2026-02-05 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0037_allocation_created_at_allocation_purchase_order_item_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocation",
            name="purchase_order_item",
        ),
    ]
