# Generated by Django 5.2.8 on 2026-02-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_remove_allocation_purchase_order_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('-slug',), 'permissions': [('manage_purchase_orders', 'Can manage purchase orders'), ('manage_stock', 'Can manage stock')]},
        ),
    ]
