# Generated by Django 5.2.8 on 2026-02-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_purchaseorderitem_quantity_fulfilled"),
        ("order", "0221_order_inco_term_pick_pickitem_and_more"),
        ("warehouse", "0039_alter_warehouse_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fulfillment_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_sources",
                        to="order.fulfillmentline",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_sources",
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "indexes": [
                    models.Index(
                        fields=["fulfillment_line", "purchase_order_item"],
                        name="warehouse_f_fulfill_64c500_idx",
                    ),
                    models.Index(
                        fields=["purchase_order_item", "-created_at"],
                        name="warehouse_f_purchas_9c5831_idx",
                    ),
                ],
            },
        ),
    ]
