name: Bug Report
description: Report a bug or defect
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Type
        Bug

  - type: textarea
    id: why
    attributes:
      label: Why
      description: Explain the business motivation and impact with respect to current Dirac bottlenecks
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug? What is the expected vs actual behavior?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, error messages, environment details, etc.
    validations:
      required: false
