from enum import Enum


class ProductErrorCode(Enum):
    ALREADY_EXISTS = "already_exists"
    ATTRIBUTE_ALREADY_ASSIGNED = "attribute_already_assigned"
    ATTRIBUTE_CANNOT_BE_ASSIGNED = "attribute_cannot_be_assigned"
    ATTRIBUTE_VARIANTS_DISABLED = "attribute_variants_disabled"
    MEDIA_ALREADY_ASSIGNED = "media_already_assigned"
    DUPLICATED_INPUT_ITEM = "duplicated_input_item"
    GRAPHQL_ERROR = "graphql_error"
    INVALID = "invalid"
    INVALID_PRICE = "invalid_price"
    PRODUCT_WITHOUT_CATEGORY = "product_without_category"
    NOT_PRODUCTS_IMAGE = "not_products_image"
    NOT_PRODUCTS_VARIANT = "not_products_variant"
    NOT_FOUND = "not_found"
    OWNED_WAREHOUSE = "owned_warehouse"
    REQUIRED = "required"
    UNIQUE = "unique"
    VARIANT_NO_DIGITAL_CONTENT = "variant_no_digital_content"
    CANNOT_MANAGE_PRODUCT_WITHOUT_VARIANT = "cannot_manage_product_without_variant"
    PRODUCT_NOT_ASSIGNED_TO_CHANNEL = "product_not_assigned_to_channel"
    UNSUPPORTED_MEDIA_PROVIDER = "unsupported_media_provider"
    PREORDER_VARIANT_CANNOT_BE_DEACTIVATED = "preorder_variant_cannot_be_deactivated"
    # Product ingestion error codes
    SHEET_INTEGRITY_ERROR = "sheet_integrity_error"
    SIZE_QTY_UNPARSEABLE = "size_qty_unparseable"
    CURRENCY_INCOMPATIBLE = "currency_incompatible"
    DUPLICATE_PRODUCTS = "duplicate_products"
    MISSING_DATABASE_SETUP = "missing_database_setup"
    DUPLICATE_PRODUCT_NAMES = "duplicate_product_names"
    MISSING_REQUIRED_FIELDS = "missing_required_fields"
    COLUMN_MAPPING_INVALID = "column_mapping_invalid"
    FILE_NOT_FOUND = "file_not_found"
    FILE_EXPIRED = "file_expired"


class CollectionErrorCode(Enum):
    DUPLICATED_INPUT_ITEM = "duplicated_input_item"
    GRAPHQL_ERROR = "graphql_error"
    INVALID = "invalid"
    NOT_FOUND = "not_found"
    REQUIRED = "required"
    UNIQUE = "unique"
    CANNOT_MANAGE_PRODUCT_WITHOUT_VARIANT = "cannot_manage_product_without_variant"


class ProductVariantBulkErrorCode(Enum):
    ATTRIBUTE_ALREADY_ASSIGNED = "attribute_already_assigned"
    ATTRIBUTE_CANNOT_BE_ASSIGNED = "attribute_cannot_be_assigned"
    ATTRIBUTE_VARIANTS_DISABLED = "attribute_variants_disabled"
    DUPLICATED_INPUT_ITEM = "duplicated_input_item"
    GRAPHQL_ERROR = "graphql_error"
    INVALID = "invalid"
    INVALID_PRICE = "invalid_price"
    NOT_PRODUCTS_VARIANT = "not_products_variant"
    NOT_FOUND = "not_found"
    REQUIRED = "required"
    UNIQUE = "unique"
    PRODUCT_NOT_ASSIGNED_TO_CHANNEL = "product_not_assigned_to_channel"
    STOCK_ALREADY_EXISTS = "stock_already_exists"


class ProductBulkCreateErrorCode(Enum):
    ATTRIBUTE_ALREADY_ASSIGNED = "attribute_already_assigned"
    ATTRIBUTE_CANNOT_BE_ASSIGNED = "attribute_cannot_be_assigned"
    ATTRIBUTE_VARIANTS_DISABLED = "attribute_variants_disabled"
    BLANK = "blank"
    MAX_LENGTH = "max_length"
    DUPLICATED_INPUT_ITEM = "duplicated_input_item"
    GRAPHQL_ERROR = "graphql_error"
    INVALID = "invalid"
    INVALID_PRICE = "invalid_price"
    PRODUCT_WITHOUT_CATEGORY = "product_without_category"
    NOT_FOUND = "not_found"
    REQUIRED = "required"
    UNIQUE = "unique"
    PRODUCT_NOT_ASSIGNED_TO_CHANNEL = "product_not_assigned_to_channel"
    UNSUPPORTED_MEDIA_PROVIDER = "unsupported_media_provider"
