# Generated by Django 5.2.8 on 2026-01-12 16:21

from django.db import connection, migrations


def grant_saleor_permissions(apps, schema_editor):
    """Grant permissions only in non-test environments."""
    # Skip this migration in test environments (databases named test_*)
    if connection.settings_dict["NAME"].startswith("test_"):
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            GRANT ALL PRIVILEGES ON DATABASE saleor TO saleor;
            GRANT USAGE ON SCHEMA public TO saleor;
            GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO saleor;
            GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO saleor;
            GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO saleor;
            GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT USAGE ON TYPES TO saleor;
            """
        )


def revoke_saleor_permissions(apps, schema_editor):
    """Revoke permissions only in non-test environments."""
    # Skip this migration in test environments
    if connection.settings_dict["NAME"].startswith("test_"):
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            -- Revoke privileges (for rollback)
            REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM saleor;
            REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM saleor;
            REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM saleor;
            REVOKE USAGE ON SCHEMA public FROM saleor;

            -- Remove default privileges
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
              REVOKE ALL ON TABLES FROM saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
              REVOKE ALL ON SEQUENCES FROM saleor;
            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
              REVOKE EXECUTE ON FUNCTIONS FROM saleor;
            """
        )


class Migration(migrations.Migration):
    """Grant the saleor role permissions on all tables, sequences, and functions.

    This migration runs AFTER all Saleor tables have been created by the superuser.
    Skips execution in test environments.
    """

    dependencies = []

    operations = [
        migrations.RunPython(
            grant_saleor_permissions,
            reverse_code=revoke_saleor_permissions,
        ),
    ]
