# Generated by Django 5.2.8 on 2026-02-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("invoice", "0011_invoice_invoice_created_at_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="purchase_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice",
                to="inventory.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[
                    ("final", "A final invoice. Can be uploaded to Xero."),
                    (
                        "proforma",
                        "An invoice _sometimes_ sent before a final invoice with expected charge.",
                    ),
                ],
                default="final",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="xero_invoice_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
