# Generated by Django 5.2.8 on 2026-02-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0012_invoice_purchase_order_invoice_type_and_more"),
        ("order", "0223_add_deposit_and_proforma_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fulfillment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proforma_invoice",
                to="order.fulfillment",
            ),
        ),
    ]
