# Generated by Django 5.2.8 on 2026-02-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0013_add_deposit_and_proforma_fields"),
        ("order", "0233_remove_fulfillment_quote_pdf_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="fulfillment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="order.fulfillment",
            ),
        ),
    ]
