# Generated by Django 5.2.8 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_purchaseorderitem_quantity_fulfilled"),
        ("invoice", "0014_alter_invoice_fulfillment"),
        ("order", "0233_remove_fulfillment_quote_pdf_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fulfillment__isnull", False)),
                fields=("fulfillment", "type"),
                name="unique_invoice_per_fulfillment_type",
            ),
        ),
    ]
