# Generated by Django 5.2.8 on 2026-02-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0219_merge_20251212_0955"),
        ("shipping", "0038_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="shipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fulfillments",
                to="shipping.shipment",
            ),
        ),
    ]
