# Generated by Django 5.2.8 on 2026-02-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("order", "0220_fulfillment_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="inco_term",
            field=models.CharField(
                choices=[
                    ("EXW", "Ex Works"),
                    ("FCA", "Free Carrier"),
                    ("CPT", "Carriage Paid To"),
                    ("CIP", "Carriage and Insurance Paid To"),
                    ("DAP", "Delivered At Place"),
                    ("DPU", "Delivered at Place Unloaded"),
                    ("DDP", "Delivered Duty Paid"),
                    ("FAS", "Free Alongside Ship"),
                    ("FOB", "Free On Board"),
                    ("CFR", "Cost and Freight"),
                    ("CIF", "Cost Insurance and Freight"),
                ],
                default="DDP",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When picking was started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When picking was completed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this pick"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who completed picking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picks_completed",
                        to="account.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the pick",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picks_created",
                        to="account.user",
                    ),
                ),
                (
                    "fulfillment",
                    models.OneToOneField(
                        help_text="Fulfillment being picked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick",
                        to="order.fulfillment",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who started picking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picks_started",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_to_pick",
                    models.PositiveIntegerField(
                        help_text="Quantity that needs to be picked (from fulfillment line)"
                    ),
                ),
                (
                    "quantity_picked",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity physically picked from warehouse"
                    ),
                ),
                (
                    "picked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this item was marked as fully picked",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about picking this specific item"
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        help_text="Which order line this item picks for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_items",
                        to="order.orderline",
                    ),
                ),
                (
                    "pick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.pick",
                    ),
                ),
                (
                    "picked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who picked this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pick_items_picked",
                        to="account.user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["fulfillment", "-created_at"],
                name="order_pick_fulfill_6a47fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["status", "-created_at"], name="order_pick_status_5bc471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickitem",
            index=models.Index(
                fields=["pick", "order_line"], name="order_picki_pick_id_6f993e_idx"
            ),
        ),
    ]
