# Generated by Django 5.2.8 on 2026-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0221_order_inco_term_pick_pickitem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fulfillment",
            old_name="tracking_number",
            new_name="tracking_url",
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="tracking_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tracking URL or number from carrier",
                max_length=255,
            ),
        ),
    ]
