# Generated by Django 5.2.8 on 2026-02-13 09:55

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0222_rename_fulfillment_tracking_to_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="deposit_allocated_amount",
            field=models.DecimalField(
                decimal_places=3, default=Decimal(0), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="proforma_invoice_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="proforma_invoice_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="deposit_required",
            field=models.BooleanField(default=False),
        ),
    ]
