# Generated by Django 5.2.8 on 2026-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0223_add_deposit_and_proforma_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="deposit_payment_id",
        ),
        migrations.AlterField(
            model_name="fulfillment",
            name="proforma_invoice_paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when proforma invoice was marked as paid. IMPORTANT: This field is manually set by users, as the system does not track payments internally. It is subject to user error and should NOT be used for accounting purposes. Its sole purpose is to unblock fulfillment workflow by indicating payment has been received.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="deposit_paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the deposit threshold was met by cumulative Xero payments.",
                null=True,
            ),
        ),
    ]
