# Generated by Django 5.2.8 on 2026-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0224_remove_old_deposit_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="proforma_invoice_paid",
        ),
        migrations.RemoveField(
            model_name="fulfillment",
            name="proforma_invoice_paid_at",
        ),
    ]
