# Generated by Django 5.2.8 on 2026-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0225_remove_proforma_invoice_paid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillment",
            name="quote_pdf_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the quote PDF hosted by the Xero integration app.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="xero_proforma_prepayment_id",
            field=models.CharField(
                blank=True,
                help_text="Xero prepayment UUID for the proforma payment on this fulfillment.",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="xero_quote_id",
            field=models.CharField(
                blank=True,
                help_text="Xero Quote UUID for the proforma quote linked to this fulfillment.",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fulfillment",
            name="xero_quote_number",
            field=models.CharField(
                blank=True,
                help_text="Xero Quote number (e.g. Q-1234).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="xero_deposit_prepayment_id",
            field=models.CharField(
                blank=True,
                help_text="Xero prepayment UUID for the deposit on this order.",
                max_length=36,
                null=True,
            ),
        ),
    ]
