# Generated by Django 5.2.8 on 2026-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0227_order_xero_bank_account_code"),
        ("warehouse", "0040_fulfillmentsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="allowed_warehouses",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders_with_restricted_warehouses",
                to="warehouse.warehouse",
            ),
        ),
    ]
