# Generated by Django 5.2.8 on 2026-02-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0228_allowed_warehouses"),
        ("tax", "0012_taxclasscountryrate_xero_tax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="tax_class_country_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tax.taxclasscountryrate",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="xero_tax_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
