# Generated by Django 5.2.8 on 2026-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0229_orderline_tax_class_country_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_xero_tax_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
