# Generated by Django 5.2.8 on 2026-02-26 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0232_order_xero_bank_account_sort_code_and_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulfillment",
            name="quote_pdf_url",
        ),
    ]
