# Generated by Django 5.2.8 on 2026-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xero_contact_id',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                db_index=True,
                help_text='Xero contact ID for this customer. Auto-populated from Xero API.',
            ),
        ),
    ]
