# Generated by Django 5.2.8 on 2026-02-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("shipping", "0038_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="purchase_order_items",
                to="shipping.shipment",
            ),
        ),
    ]
