# Generated by Django 5.2.8 on 2026-02-03 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_purchaseorderitem_shipment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorderitem",
            old_name="quantity",
            new_name="quantity_ordered",
        ),
    ]
