# Generated by Django 5.2.8 on 2026-02-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("inventory", "0003_rename_quantity_to_quantity_ordered"),
        ("shipping", "0038_shipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="quantity_received",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="unit_price_amount",
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="total_price_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Total invoice amount for this POI (quantity × unit price)",
                max_digits=20,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When receiving was completed and processed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this receipt"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who completed receiving",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts_completed",
                        to="account.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who started receiving",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts_created",
                        to="account.user",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        help_text="Inbound shipment being received",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        help_text="Quantity physically received in this receipt line"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this specific item/batch was scanned",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this specific line (damage, etc.)",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        help_text="Which POI this line receives against",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_lines",
                        to="inventory.purchaseorderitem",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.receipt",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Warehouse staff who scanned this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItemAdjustment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Change in quantity (negative for losses, positive for gains)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("shrinkage_theft", "Shrinkage - Theft"),
                            ("shrinkage_damage", "Shrinkage - Damage"),
                            ("shrinkage_unknown", "Shrinkage - Unknown"),
                            ("cycle_count_neg", "Cycle Count - Shortage Found"),
                            ("cycle_count_pos", "Cycle Count - Excess Found"),
                            ("invoice_variance", "Invoice Variance"),
                            ("delivery_short", "Delivery Short"),
                        ],
                        help_text="Why this adjustment was made",
                        max_length=32,
                    ),
                ),
                (
                    "affects_payable",
                    models.BooleanField(
                        default=False,
                        help_text="True if supplier credits us for this adjustment (invoice variance, delivery short). False if we eat the loss (shrinkage, damage).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional details about the adjustment"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this adjustment was processed (stock updated, allocations adjusted)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this adjustment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.user",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        help_text="Which POI batch this adjustment applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="inventory.purchaseorderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purchase_order_item", "-created_at"],
                        name="inventory_p_purchas_4c059c_idx",
                    ),
                    models.Index(
                        fields=["reason", "-created_at"],
                        name="inventory_p_reason_a35fe2_idx",
                    ),
                    models.Index(
                        fields=["processed_at"], name="inventory_p_process_8da8e6_idx"
                    ),
                    models.Index(
                        fields=["affects_payable", "-created_at"],
                        name="inventory_p_affects_51db48_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["shipment", "-created_at"],
                name="inventory_r_shipmen_f91216_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["status", "-created_at"], name="inventory_r_status_d32920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiptline",
            index=models.Index(
                fields=["receipt", "purchase_order_item"],
                name="inventory_r_receipt_4db6fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receiptline",
            index=models.Index(
                fields=["received_at"], name="inventory_r_receive_98ac2a_idx"
            ),
        ),
    ]
