# Generated by Django 5.2.8 on 2026-02-05 15:16

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_repopulate_user_number_of_orders"),
        ("app", "0037_app_extensions_loosen_mount"),
        ("inventory", "0004_remove_purchaseorderitem_quantity_received_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("created", "Purchase order created"),
                            ("confirmed", "Purchase order confirmed with supplier"),
                            ("received", "Goods received at warehouse"),
                            ("cancelled", "Purchase order cancelled"),
                            ("item_added", "Item added to purchase order"),
                            ("item_removed", "Item removed from purchase order"),
                            ("adjustment_created", "Inventory adjustment created"),
                            ("adjustment_processed", "Inventory adjustment processed"),
                            ("shipment_assigned", "Shipment assigned"),
                            ("note_added", "Note added"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        help_text="App that triggered this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.app",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchase order this event relates to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific POI this event relates to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.purchaseorderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["date"], name="inventory_poevent_date_idx"
                    ),
                    models.Index(
                        fields=["purchase_order", "date"],
                        name="inventory_p_purchas_706a1d_idx",
                    ),
                    models.Index(
                        fields=["purchase_order_item", "date"],
                        name="inventory_p_purchas_6c50fc_idx",
                    ),
                    models.Index(fields=["type"], name="inventory_p_type_8eb258_idx"),
                ],
            },
        ),
    ]
