# Generated by Django 5.2.8 on 2026-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_purchaseorderevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="quantity_fulfilled",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
